# ログ
logger:
  filePath: "log/log.log"
  filePattern: "%Y-%m-%d %T.%e [%L] [%s] %v"
  consolePattern: "%^[%D][%s] %v%$"
  level: "trace"

# ウィンドウ
window:
  title: "Window"
  width: 1920
  height: 1080

# カメラ
camera:
  position: [0.0, 5.0, -10.0]
  yaw: 0.0
  pitch: -0.5
  moveSpeed: 15.0
  rotateSpeed: 0.05
  zoomSpeed: 20.0
  nearZ: 1.0
  farZ: 1000.0

# シェーダー
shader:
  basicVS: "Asset/shader/BasicVS.cso"
  basicPS: "Asset/shader/BasicPS.cso"

# モデル
modelpath: "Asset/model/cube/cube.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-1k.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-4k.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-16k.obj"
# modelpath: "Asset/model/sponza/sponza.obj"
# modelpath: "Asset/model/teapot/teapot.obj"
