# ログ
logger:
  filePath: "log/log.log"
  filePattern: "%Y-%m-%d %T.%e [%L] [%s] %v"
  consolePattern: "%^[%D][%s] %v%$"
  level: "trace"

# ウィンドウ
window:
  title: "Window"
  width: 1920
  height: 1080

# グラフィックス
Graphics:
  m_enableWireframe: false
  m_cullMode: D3D11_CULL_BACK
  m_frontCounterClockwise: false
  # clearColor: [0.0, 0.0, 0.0, 1.0]
  # enableVSync: false
  # enableMSAA: false
  # msaaCount: 4
  # enableDepthTest: true
  # enableDepthWrite: true
  # cullFace: "back"
  # enableBlend: false
  # blendSrc: "src_alpha"
  # blendDst: "one_minus_src_alpha"
  # blendOp: "add"

# カメラ
camera:
  position: [0.0, 3.0, -5.0]
  yaw: 0.0
  pitch: -0.5
  moveSpeed: 5.0
  rotateSpeed: 0.05
  zoomSpeed: 10.0
  nearZ: 1.0
  farZ: 1000.0

# シェーダー
shader:
  basicVS: "Asset/shader/BasicVS.cso"
  basicPS: "Asset/shader/BasicPS.cso"

# モデル
modelpath: "Asset/model/cube/cube.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-1k.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-4k.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-16k.obj"
# modelpath: "Asset/model/sponza/sponza.obj"
# modelpath: "Asset/model/teapot/teapot.obj"
