# ディレクトリ
Directory:
  asset: "asset"

# ログ
logger:
  filePath: "log/log.log"
  filePattern: "%Y-%m-%d %T.%e [%L] [%s] %v"
  consolePattern: "%^[%D][%s] %v%$"
  level: "trace"

# ウィンドウ
window:
  title: "Window"
  width: 1920
  height: 1080

# グラフィックス
Graphics:
  m_enableWireframe: false
  m_cullMode: D3D11_CULL_NONE
  m_frontCounterClockwise: false
  # clearColor: [0.0, 0.0, 0.0, 1.0]
  # enableVSync: false
  # enableMSAA: false
  # msaaCount: 4
  # enableDepthTest: true
  # enableDepthWrite: true
  # cullFace: "back"
  # enableBlend: false
  # blendSrc: "src_alpha"
  # blendDst: "one_minus_src_alpha"
  # blendOp: "add"

# GUI
GUI:
  m_openMouseCapture: false
  m_openGraphicsConfig: false
  m_openCameraConfig: false
  m_openLightConfig: false

# カメラ
Camera:
  m_position: [0.0, 3.0, -5.0]
  m_target: [0.0, 0.0, 0.0]
  m_moveSpeed: 1.0
  m_nearZ: 0.01
  m_farZ: 100.0

# ライト
DirectionalLight:
  m_direction: [1.0, -1.0, 1.0]
  m_color: [1.0, 1.0, 1.0]
  m_ambient: [0.1, 0.1, 0.1]

# シェーダー
Shader:
  Basic:
    VS: "shader/BasicVS.cso"
    PS: "shader/BasicPS.cso"

# モデル
# modelpath: "asset/model/cube/cube.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-1k.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-4k.obj"
# modelpath: "Asset/model/sphere/sphere-cylcoords-16k.obj"
modelpath: "Asset/model/sponza/sponza.obj"
# modelpath: "Asset/model/teapot/teapot.obj"
